title: Talk is Cheap. Show me the Code.
description: "Stay Focused & Keep Shipping."
author:
  name: "chensheng"
  email: "chenshengxmu@163.com"
  url: "https://biheap.com/hacker"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 10
paginate_path: /page:num/

collections:
  zhan-guo-che:
    output: true


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "chensheng"
year : "2019"

