title: Stay Focused & Keep Shipping.
description: "Talk is Cheap. Show me the Code."
author:
  name: "chensheng"
  email: "chenshengxmu@163.com"
  url: "https://biheap.com/hacker"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 10
paginate_path: /page:num/

collections:
  zhan-guo-che:
    output: true
  array:
    output: true
  list:
    output: true
  stack:
    output: true
  queue:
    output: true
  tree:
    output: true
  matrix:
    output: true
  graph:
    output: true



defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "chensheng"
year : "2019"

